---
name: builds
on:
  pull_request:
    branches:
      - main

jobs:
  BuildTestAndCheck:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repo
      - name: checkout-module
        uses: actions/checkout@v3
        with:
          path: Brownserve.PSTools
      # Step 2: Run the build script
      - name: run-build-script
        shell: pwsh
        run: |
            ./Brownserve.PSTools/.build/build.ps1 `
              -GitHubRepoName 'Brownserve.PSTools' `
              -BranchName $env:GITHUB_REF `
              -Build 'BuildTestAndCheck' `
              -Verbose
      # Step 3: Send a notification to Slack
      - name: notify-slack
        shell: pwsh
        if: ${{ always() }}
        env:
          BUILD_NOTIFICATION_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          BUILD_BRANCH: ${{ github.head_ref }}
        run: |
            ./Brownserve.PSTools/.build/_init.ps1
            Send-BuildNotification `
              -BuildName ${{ github.job }} `
              -BuildStatus ${{ job.status }} `
              -Webhook $env:BUILD_NOTIFICATION_WEBHOOK `
              -RepoBranch $env:BUILD_BRANCH `
              -RepoName $global:BrownserveRepoName
