---
name: builds
on: 
  pull_request:
    

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    # Checkout this repo
    steps:
      - name: checkout-module
        uses: actions/checkout@v3
        with: 
          path: Brownserve.PSTools
          fetch-depth: 2
    # Run the build script
      - name: run-build-script
        shell: pwsh
        run: |
            ./Brownserve.PSTools/.build/build.ps1 `
              -GitHubRepoName 'Brownserve.PSTools' `
              -BranchName $env:GITHUB_REF `
              -Build 'BuildImportGenerateDocsTest' `
              -Verbose
      - name: notify-slack
        shell: pwsh
        if: ${{ always() }}
        env:
          BUILD_NOTIFICATION_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          BUILD_BRANCH: ${{ github.head_ref }}
        run: |
            ./Brownserve.PSTools/.build/_init.ps1
            Send-BuildNotification `
              -BuildName ${{ github.job }} `
              -BuildStatus ${{ job.status }} `
              -Webhook $env:BUILD_NOTIFICATION_WEBHOOK `
              -RepoBranch $env:BUILD_BRANCH `
              -RepoName $global:BrownserveRepoName
          