---
name: builds
on: 
  pull_request:
    

jobs:
  build-and-test:
    runs-on: windows-latest
    # Checkout this repo
    steps:
      - name: checkout-module
        uses: actions/checkout@v2
        with: 
          path: Brownserve.BuildTools
    # Run the build script
      - name: run-build-script
        shell: pwsh
        run: |
            ./Brownserve.BuildTools/.build/build.ps1 -BranchName $env:GITHUB_REF -Verbose
      - name: notify-slack
        shell: pwsh
        if: ${{ always() }}
        env:
          BUILD_NOTIFICATION_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          BUILD_BRANCH: ${{ github.head_ref }}
        run: |
            Get-Module
            ./Brownserve.BuildTools/.build/_init.ps1
            Send-BuildNotification -BuildName ${{ github.job }} -BuildStatus ${{ job.status }}
          