---
name: release
on:
  workflow_dispatch:
    

jobs: 
  release:
    runs-on: windows-latest
    # Checkout this repo
    steps:
      - name: checkout-module
        uses: actions/checkout@v2
        with: 
          path: Brownserve.PSTools
    # Run the build script
      - name: run-build-script
        shell: pwsh
        env:
          GitHubPAT: ${{ secrets.AUTOMATED_BUILD_GITHUB_PAT }}
          NugetFeedAPIKey: ${{ secrets.NUGET_API_KEY }}
          PSGalleryAPIKey: ${{ secrets.PSGALLERY_API_KEY }}
        run: |
            ./Brownserve.PSTools/.build/build.ps1 -BranchName $env:GITHUB_REF -Build 'release' -NugetFeedAPIKey $env:NugetFeedAPIKey -PSGalleryAPIKey $env:PSGalleryAPIKey -Verbose
    # Do a Slack notification
      - name: notify-slack
        shell: pwsh
        if: ${{ always() }}
        env:
          BUILD_NOTIFICATION_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          BUILD_BRANCH: ${{ github.ref }}
        run: |
            ./Brownserve.PSTools/.build/_init.ps1
            Send-BuildNotification -BuildName ${{ github.job }} -BuildStatus ${{ job.status }} -Webhook $env:BUILD_NOTIFICATION_WEBHOOK